# Generated by Django 5.1.1 on 2024-09-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota_webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaches',
            name='prof_ID',
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='course_ID',
        ),
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Teaches',
        ),
    ]
